deploy-infra:
    tofu apply

lock-www:
    nix flake update website

test-deploy: lock-www
    nixos-rebuild --target-host root@49.13.127.186 -I nixos-config=./configuration.nix --flake ".#website" dry-build

deploy: lock-www
    nixos-rebuild --target-host root@49.13.127.186 -I nixos-config=./configuration.nix --flake ".#website" switch
