name: "Build & Test"

on:
  push:
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v15
      with:
        name: danielgafni
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Install devenv
      # devenv 2.2.x can fail with invalid store paths: https://github.com/cachix/devenv/issues/3064
      run: nix profile install github:cachix/devenv/v2.3.1 --accept-flake-config
    - name: Lint (git hooks)
      run: devenv shell -- prek run --all-files
    - name: Build site
      run: devenv shell -- zola --root www build

  deploy:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    environment:
      name: cloudflare-pages
      url: https://gafni.dev
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: danielgafni
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Install devenv
        run: nix profile install github:cachix/devenv/v2.3.1 --accept-flake-config
      - run: devenv shell -- zola --root www build
      - run: devenv shell -- wrangler pages deploy www/public --project-name=gafni-dev --branch=master
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: 3f09b742c8d0c0b4fefb8b9dc9a1899d
