name: "Build & Test"
  
on:
  push:
  workflow_dispatch:
jobs:
  test-www:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./www
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: danielgafni
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .
    - run: nix flake check

  test-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: danielgafni
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixosConfigurations.website.config.system.build.toplevel
    - run: nix flake check

