name: "Build & Test"
  
on:
  push:
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: danielgafni
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check
    - run: nix build .
      working-directory: ./www
    - run: nix flake check
      working-directory: ./www
    - run: nix-shell -p just --run 'just lock-www'
      working-directory: ./infra
    - run: nix-shell -p nixos-rebuild --run 'nixos-rebuild --accept-flake-config --flake .#website build'
      working-directory: ./infra
    - run: nix flake check
      working-directory: ./infra

  deploy:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GAFNI_DEV_SSH_PRIVATE_KEY }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: danielgafni
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-env -i just
      - run: just nixos-rebuild
        working-directory: infra
