name: "Build & Test"
  
on:
  push:
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: danielgafni
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .
      working-directory: ./www
    - run: nix flake check
      working-directory: ./www
    - run: nix build --accept-flake-config .#nixosConfigurations.website.config.system.build.toplevel
      working-directory: ./infra
    - run: nix flake check
      working-directory: ./infra

