name: Deploy GitHub Pages Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Zola Build
        if: github.event.action != 'closed'
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          BUILD_DIR: ./www
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts --base-url https://danielgafni.github.io/website/pr-preview/pr-${{ github.event.number }}

      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./www/public
